//SimAS  /  Editor
//Editor

package es.uco.simas.editor;

import javax.swing.JOptionPane;
import es.uco.simas.util.gramatica.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import com.itextpdf.text.DocumentException;
import es.uco.simas.centroayuda.AcercaDe;
import es.uco.simas.simulador.VentanaSimuladorAsc;
import es.uco.simas.simulador.VentanaSimuladorDesc;
import java.awt.Desktop;
import static java.awt.SystemColor.desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author vanesa
 */
public class Editor extends javax.swing.JFrame {
   Gramatica gramatica = crearGramatica();
   Editor ancestor ;         
   
   public Editor(){
       initComponents();
       
       this.jMenuItemAsc.setEnabled(false);
       this.jMenuItemDesc.setEnabled(false);
       this.jPanel2.setVisible(false);
       this.jButtonEditar.setEnabled(false);
       this.jButtonEliminar.setEnabled(false);
       this.jButtonGuardar.setEnabled(false);
       this.jButtonSimDesc.setEnabled(false);
       this.jMenuItemCerrar.setEnabled(false);
       this.jMenuItemEditar.setEnabled(false);
       this.jMenuItemGuardar.setEnabled(false);
       this.jButtonValidar.setEnabled(false);
       this.jMenuItemValidar.setEnabled(false);
       this.jButtonpdf.setEnabled(false);
       this.jLabelEstado.setEnabled(false);
       this.jButton1SimAsc.setEnabled(false);
       this.jButtonSimDesc.setEnabled(false);
       this.jMenuItemAsc.setEnabled(false);
       this.jMenuItemDesc.setEnabled(false);   
   }
    
    public Editor(Gramatica gr) {
        
        this.gramatica = gr;  
        DefaultListModel model = this.gramatica.getProducciones();
        DefaultListModel model2 = new DefaultListModel();
        initComponents();
        DefaultListModel noTerminales = new DefaultListModel();
        ArrayList<NoTerminal> noTerm = this.gramatica.getNoTerm();

       this.jButton1SimAsc.setEnabled(false);
       this.jButtonSimDesc.setEnabled(false);
       this.jMenuItemAsc.setEnabled(false);
       this.jMenuItemDesc.setEnabled(false);
       this.jButtonEditar.setEnabled(true);
       this.jButtonEliminar.setEnabled(true);
       this.jButtonGuardar.setEnabled(true);
       this.jMenuItemCerrar.setEnabled(true);
       this.jMenuItemEditar.setEnabled(true);
       this.jMenuItemGuardar.setEnabled(true);
       this.jButtonValidar.setEnabled(true);
       this.jMenuItemValidar.setEnabled(true);
       if(gr.getEstado()==1){
           this.jLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/aceptar.png")));
           this.jLabelEstado.setText("La gramática está validada");
           this.jButton1SimAsc.setEnabled(true);
           this.jButtonSimDesc.setEnabled(true);
           this.jMenuItemAsc.setEnabled(true);
           this.jMenuItemDesc.setEnabled(true);
       }else {
           this.jLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/cancelar.png")));
           this.jLabelEstado.setText("La gramática no está validada");
           this.jButton1SimAsc.setEnabled(false);
           this.jButtonSimDesc.setEnabled(false);
       }
             
        this.jTextFieldNombre.setText(this.gramatica.getNombre());
        this.jTextAreaDesc.setText(this.gramatica.getDescripcion());
        this.jTextAreaDesc.setLineWrap(true);
        this.jTextAreaDesc.setWrapStyleWord(true);
        if(this.gramatica.getSimbInicial()!=null)
            this.jTextFieldSI.setText(this.gramatica.getSimbInicial());
        if(this.gramatica.getNoTerminales()!= null){           
            int v=0;
            while(v < noTerm.size()){
                noTerminales.addElement(noTerm.get(v).getNombre());
                v++;
            }
            this.jListNT.setModel(noTerminales);
        }
        if(this.gramatica.getTerminales() != null)
            this.jListT.setModel(this.gramatica.getTerminales());
        if(this.gramatica.getProducciones() != null){
            int i =0;
            Object obj;
            obj = "P {";
            model2.addElement(obj);
            while (i < model.size()){
                obj = "   "+(i+1)+")   "+model.getElementAt(i);
                model2.addElement(obj);
                i++;
            }
            obj ="}";
            model2.addElement(obj);
            this.jListProd.setModel(model2);
        }                              
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAñadir = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        jButtonpdf = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonSimDesc = new javax.swing.JButton();
        jButton1SimAsc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNT = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListT = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListProd = new javax.swing.JList();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldSI = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jLabelEstado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEditor = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jMenuItemValidar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuSimulador = new javax.swing.JMenu();
        jMenuItemDesc = new javax.swing.JMenuItem();
        jMenuItemAsc = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor Gramática Contexto Libre");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(233, 244, 244));

        jToolBar1.setRollover(true);

        jButtonAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/nueva.png"))); // NOI18N
        jButtonAñadir.setToolTipText("Nueva Gramática");
        jButtonAñadir.setFocusable(false);
        jButtonAñadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAñadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAñadir);

        jButtonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/abrir.png"))); // NOI18N
        jButtonAbrir.setToolTipText("Abrir Gramática");
        jButtonAbrir.setFocusable(false);
        jButtonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAbrir);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/guardar.png"))); // NOI18N
        jButtonGuardar.setToolTipText("Guardar Gramática");
        jButtonGuardar.setFocusable(false);
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGuardar);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/editar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar Gramática");
        jButtonEditar.setFocusable(false);
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEditar);

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/eliminar.png"))); // NOI18N
        jButtonEliminar.setToolTipText("Cerrar Gramática");
        jButtonEliminar.setFocusable(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEliminar);

        jButtonValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/validar.png"))); // NOI18N
        jButtonValidar.setToolTipText("Validar Gramatica");
        jButtonValidar.setFocusable(false);
        jButtonValidar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonValidar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonValidar);

        jButtonpdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/informeGr.png"))); // NOI18N
        jButtonpdf.setToolTipText("Informe Gramática");
        jButtonpdf.setFocusable(false);
        jButtonpdf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonpdf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpdfActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonpdf);
        jToolBar1.add(jSeparator1);

        jButtonSimDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/simularDesc.png"))); // NOI18N
        jButtonSimDesc.setMnemonic('S');
        jButtonSimDesc.setToolTipText("Simulación Descendente");
        jButtonSimDesc.setFocusable(false);
        jButtonSimDesc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSimDesc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSimDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimDescActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSimDesc);

        jButton1SimAsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/simularAsc.png"))); // NOI18N
        jButton1SimAsc.setMnemonic('S');
        jButton1SimAsc.setToolTipText("Simulación Ascendente");
        jButton1SimAsc.setFocusable(false);
        jButton1SimAsc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1SimAsc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1SimAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SimAscActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1SimAsc);
        jToolBar1.add(jSeparator2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/salir.png"))); // NOI18N
        jButton2.setToolTipText("Salir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jPanel2.setBackground(new java.awt.Color(233, 244, 244));
        jPanel2.setOpaque(false);

        jLabelNom.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(33, 77, 72));
        jLabelNom.setText("Nombre: ");

        jLabelDesc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelDesc.setForeground(new java.awt.Color(33, 77, 72));
        jLabelDesc.setText("Descripción: ");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 77, 72));
        jLabel1.setText("Símbolos No Terminales:");

        jScrollPane1.setViewportView(jListNT);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 77, 72));
        jLabel2.setText("Símbolos Terminales:");

        jScrollPane2.setViewportView(jListT);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 77, 72));
        jLabel3.setText("Símbolo inicial: ");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 77, 72));
        jLabel4.setText("Producciones:");

        jScrollPane3.setViewportView(jListProd);

        jTextFieldNombre.setEditable(false);

        jTextFieldSI.setEditable(false);

        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextAreaDesc.setEditable(false);
        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDesc);

        jLabelEstado.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelNom)
                                        .addGap(34, 34, 34)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabelEstado))
                                    .addComponent(jLabelDesc)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSI, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDesc)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jMenuEditor.setMnemonic('E');
        jMenuEditor.setText("Editor");

        jMenuItemNuevo.setMnemonic('N');
        jMenuItemNuevo.setText("Nueva Gramática");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
                jButtonAñadirActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemNuevo);

        jMenuItemAbrir.setMnemonic('A');
        jMenuItemAbrir.setText("Abrir Gramática");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemAbrir);

        jMenuItemGuardar.setText("Guardar Gramática");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemGuardar);

        jMenuItemEditar.setMnemonic('D');
        jMenuItemEditar.setText("Editar Gramática");
        jMenuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemEditar);

        jMenuItemCerrar.setMnemonic('C');
        jMenuItemCerrar.setText("Cerrar Gramática");
        jMenuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemCerrar);

        jMenuItemValidar.setMnemonic('V');
        jMenuItemValidar.setText("Validar Gramática");
        jMenuItemValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidarActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemValidar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jMenuEditor.add(jMenuItemSalir);

        jMenuBar1.add(jMenuEditor);

        jMenuSimulador.setMnemonic('S');
        jMenuSimulador.setText("Simulador");

        jMenuItemDesc.setText("Simulación Descendente");
        jMenuItemDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimDescActionPerformed(evt);
            }
        });
        jMenuSimulador.add(jMenuItemDesc);

        jMenuItemAsc.setText("Simulación Ascendente");
        jMenuItemAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SimAscActionPerformed(evt);
            }
        });
        jMenuSimulador.add(jMenuItemAsc);

        jMenuBar1.add(jMenuSimulador);

        jMenuAyuda.setText("Ayuda");

        jMenuItem1.setText("Centro de Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuItem2.setText("Acerca de...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem2);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        VentanaCreacionGramatica p1 = new VentanaCreacionGramatica(this, null);
        p1.setVisible(true);
        p1.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        VentanaCreacionGramatica p1 = new VentanaCreacionGramatica(this, this.gramatica);
        p1.setVisible(true);
        p1.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSimDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimDescActionPerformed
        Gramatica gr2 = new Gramatica();
        gr2 = this.gramatica;
        VentanaSimuladorDesc simdesc = new VentanaSimuladorDesc(gr2) ;
        simdesc.setVisible(true);
        simdesc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonSimDescActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir de SimAS?", "Salir",JOptionPane.YES_NO_OPTION);
       
        if(conf==0)
           System.exit(0); 
    }                                     

    private void cerrarVentana(java.awt.event.WindowEvent evt) {                               
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir de SimAS?", "Salir",JOptionPane.YES_NO_OPTION);
       
       if(conf==0)
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       this.grabarGramatica();      
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        this.cargarGramatica();   
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       int conf = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la gramática "+this.gramatica.getNombre()+"?", "Cerrar Gramática",JOptionPane.YES_NO_OPTION);
       
       if(conf==0){
           JOptionPane.showConfirmDialog(null,"Gramática cerrada", "Cerrar Gramática", JOptionPane.DEFAULT_OPTION);
           this.dispose();
           this.gramatica.removeAll();
           Editor editor = new Editor();
           editor.setVisible(true);
           editor.setLocationRelativeTo(null);
       }
      
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jMenuItemValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidarActionPerformed
        if(this.gramatica != null)
            this.validarGramatica(this.gramatica);
    }//GEN-LAST:event_jMenuItemValidarActionPerformed

    private void jButtonpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpdfActionPerformed
          
        Boolean resultado= null;
        FileNameExtensionFilter filtro= null;
        JFileChooser selector= null;

        JFileChooser chooser = new JFileChooser();
        selector=chooser;
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Informes de gramática (.pdf)",new String[]
            {"pdf"});    
        filtro=extension;
        selector.setFileFilter(filtro);
        File fichero = new File("informeGramatica.pdf");
        selector.setSelectedFile(fichero);
        if(selector.showSaveDialog(null)==0) {
            try {            
                resultado=this.gramatica.generarInforme(selector.getSelectedFile().toString());
            } catch (DocumentException ex) {
                Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }      
    }//GEN-LAST:event_jButtonpdfActionPerformed

    private void jButton1SimAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SimAscActionPerformed
        VentanaSimuladorAsc simasc = new VentanaSimuladorAsc(this.gramatica) ;
        simasc.setVisible(true);
        simasc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1SimAscActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Desktop desktop;/* Declaro un objeto Desktop que es una nueva API en JAVA
     Para mas detalle sobre ésta API ver la siguiente Página web > 
        */
     File file = new File("src/es/uco/simas/centroayuda/SimAS.html");//declaro un Objeto File que apunte a mi archivo html
        if (Desktop.isDesktopSupported()){// si éste Host soporta esta API 
           desktop = Desktop.getDesktop();//objtengo una instancia del Desktop(Escritorio)de mi host 
            try {
                desktop.open(file);//abro el archivo con el programa predeterminado
                }
            catch (IOException ex) {
               // Logger.getLogger(MyFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
       else{ JOptionPane.showMessageDialog(null,"Lo lamento,no se puede abrir el archivo; ésta Maquina no soporta la API Desktop");
       }
        
        

        
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AcercaDe acerca = new AcercaDe();
        acerca.setVisible(true);
        acerca.setLocationRelativeTo(null);       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void cargarGramatica(){       
        Gramatica gr = new Gramatica();
        gr = this.gramatica.cargarGramatica();        
        if(gr !=null){
            this.gramatica = gr;
            this.dispose();
            Editor edit = new Editor(this.gramatica);
            edit.setVisible(true);
            edit.setLocationRelativeTo(null);
        }        
    }
    
    public void grabarGramatica(){
        int i = this.gramatica.guardarGramatica();       
        if (i==1){
           JOptionPane.showConfirmDialog(null,"Gramática guardada correctamente", "Guardar Gramática",JOptionPane.CLOSED_OPTION);
        }
    }
    
    private Gramatica crearGramatica(){
         return new Gramatica();
    }

    public Gramatica getGramatica() {
        return this.gramatica;
    }

    public void setGramatica(Gramatica gramatica) {
        this.gramatica = gramatica;
    }

    public void actualizarVisualizacion(){
        this.jListNT.setModel(this.gramatica.getNoTerminales());
        this.jListProd.setModel(this.gramatica.getProducciones());
        this.jListT.setModel(this.gramatica.getTerminales());
    }    
    
    public    void validarGramatica(Gramatica gramatica)  {        
        ArrayList<String> mensajesError = new ArrayList();
        Editor panelEditor= null;
        String mensaje= null;
        int estadoValidacion= 0;
        
         mensajesError = gramatica.validarGramatica();
         estadoValidacion= gramatica.getEstado();
        
        if(estadoValidacion == 1)    {            
            gramatica.setEstado(1);
            JOptionPane.showConfirmDialog(null, "La gramática está validada. ", "Gramática Validada",JOptionPane.CLOSED_OPTION);         
            this.dispose();
            Editor editor = new Editor(gramatica);
            editor.setVisible(true);
            editor.setLocationRelativeTo(null);            
        } else  {
          gramatica.setEstado(-1);
          JOptionPane.showConfirmDialog(null, "<html> <h4>Se han detectado los siguientes errores: </h4><br></br>"+mensajesError+"</html>", "Error. Gramática No Validada",JOptionPane.CLOSED_OPTION);         
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SimAsc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSimDesc;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonpdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JList jListNT;
    private javax.swing.JList jListProd;
    private javax.swing.JList jListT;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditor;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemAsc;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemDesc;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemValidar;
    private javax.swing.JMenu jMenuSimulador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSI;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}