//SimAS  /  Simulador
// Nueva Funcion error

package es.uco.simas.simulador;

import es.uco.simas.editor.FuncionError;
import es.uco.simas.editor.ParteAccion;
import es.uco.simas.editor.TablaLR;
import es.uco.simas.editor.TablaPredictiva;
import es.uco.simas.util.gramatica.Gramatica;
import es.uco.simas.util.gramatica.Terminal;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author vanesa
 */
public class NuevaFuncionError extends javax.swing.JFrame {

    Gramatica gramatica;
    TablaPredictiva tPredictiva;
    TablaLR tlr;
    PanelNuevaSimDescPaso4 paso4;
    PanelNuevaSimAscPaso5 paso5;
    int sim =0;
    
    public NuevaFuncionError(Gramatica gramatica, PanelNuevaSimDescPaso4 paso4) {
        this.gramatica = gramatica;        
        initComponents();
        inicializarCombos();
        this.tPredictiva = this.gramatica.getTPredictiva();        
        this.paso4 = paso4;     
        this.sim = 1;
    }
    
     public NuevaFuncionError(Gramatica gramatica, PanelNuevaSimAscPaso5 paso5, int i) {
        this.gramatica = gramatica;        
        initComponents();
        inicializarCombos();
        this.tlr = this.gramatica.getTlr();
        this.paso5 = paso5;     
        this.sim = 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Función de error");

        jPanel1.setBackground(new java.awt.Color(233, 244, 244));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Nueva Funcion Error");

        jLabel2.setText("Identificador");

        jLabel3.setText("E");

        jLabel4.setText("Acción");

        jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1. Insertar un Símbolo en la Entrada", "2. Borrar un Símbolo de la Entrada", "3. Modificar un Símbolo de la Entrada", "4. Insertar un Símbolo de la Pila", "5. Borrar un Símbolo de la Pila", "6. Modificar un Símbolo de la Pila", "7. Terminar el análisis" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo(evt);
            }
        });

        jLabel5.setText("Símbolo");

        jLabel6.setText("Mensaje");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel6))))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(209, 209, 209))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void inicializarCombos() {
        ArrayList<String> listaCombo = new ArrayList();                               
        DefaultListModel terminales= new DefaultListModel();
        int i= 0;
        terminales = this.gramatica.getTerminales();
       
        while(true) {
            if(i >= terminales.size())  {
                break;
            }
            if(i < terminales.size()) {
                listaCombo.add((String)terminales.get(i));                
                i++;
            }
        }        
        DefaultComboBoxModel combo = new DefaultComboBoxModel(listaCombo.toArray());                
        this.jComboBox2.setModel(combo);        
        
    }
      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿ Desea salir ?", "Salir",JOptionPane.YES_NO_OPTION);

        if(conf==0)
          this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<FuncionError> funciones = new ArrayList();
        if(this.sim ==1)
            funciones = this.gramatica.getTPredictiva().getFunError();
        if(this.sim ==2)
            funciones = this.gramatica.getTlr().getTAccion().getFunError();
        
        int i=0;
        if("".equals(this.jTextField1.getText().toString())){
            JOptionPane.showConfirmDialog(null, "El identificador no puede estar vacío.", "Salir",JOptionPane.CLOSED_OPTION);
        }else{
            int j=0;
            while(i < funciones.size()){                
                if(funciones.get(i).getIdentificador()==Integer.parseInt(this.jTextField1.getText())){
                    JOptionPane.showConfirmDialog(null, "El identificador está repetido.", "Salir",JOptionPane.CLOSED_OPTION);
                    j=1;
                    break;
                }else
                    i++;
            }        

            if(j==0) {
                int id = Integer.parseInt(this.jTextField1.getText().toString());
                int accion = this.jComboBox1.getSelectedIndex()+1;
                String mensaje = this.jTextField2.toString();
                Terminal term = new Terminal(this.jComboBox2.getSelectedItem().toString(),this.jComboBox2.getSelectedItem().toString());                
                FuncionError funError = new FuncionError(id,accion,mensaje ); 
                funError.setSimbolo(term);
                if(sim==1){
                    this.tPredictiva.crearFunError(funError);
                    this.gramatica.setTPredictiva(tPredictiva);
                    if(this.paso4 != null)
                        this.paso4.funcionError();
                }
                if(sim==2){
                    ParteAccion ac = this.tlr.getTAccion();
                    ac.crearFunError(funError);
                    this.tlr.setTAccion(ac);
                    this.gramatica.setTlr(this.tlr);                    
                    if(this.paso5 != null)
                        this.paso5.funcionError();
                }                               
                this.dispose();
            }
        }                
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo
        if(this.jComboBox1.getSelectedIndex() ==1 || this.jComboBox1.getSelectedIndex() ==4 || this.jComboBox1.getSelectedIndex()==6){
            this.jLabel5.setVisible(false);
            this.jComboBox2.setVisible(false);
        }else{
            this.jLabel5.setVisible(true);
            this.jComboBox2.setVisible(true);
        }        
    }//GEN-LAST:event_combo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaFuncionError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaFuncionError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaFuncionError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaFuncionError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NuevaFuncionError().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}