//SimAS  /  Simulador
//Panel Nueva Simulacion Ascendente paso 5

package es.uco.simas.simulador;

import es.uco.simas.editor.FuncionError;
import es.uco.simas.util.gramatica.Gramatica;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author Vanesa
 */
public class PanelNuevaSimAscPaso5 extends javax.swing.JPanel {

    private VentanaSimuladorAsc ventanaPadre;
    private Gramatica gramatica;
    private int funError=0;
    
    public PanelNuevaSimAscPaso5(VentanaSimuladorAsc ventanaPadre) {        
        initComponents();
        this.ventanaPadre = ventanaPadre;
        this.gramatica = ventanaPadre.getGramatica();        
        
        if(this.gramatica.getTlr().getTAccion().getFunError().size() != 0){            
            this.funcionError();
            this.funError = 1;
        }
        if(funError ==0){
            this.jButtonFinalizar.setVisible(true);
            this.jButtonUltimo.setVisible(false);
            this.jButtonSiguiente.setEnabled(false);
            this.jButtonEliminar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButtonNueva = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 244, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Funciones de Error");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/ultimo.png"))); // NOI18N
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/siguiente.png"))); // NOI18N
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/anterior.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/primero.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jCheckBox1.setText("No utilizar Funciones de error");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed1(evt);
            }
        });

        jButtonNueva.setText("Nueva Función Error  ");
        jButtonNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar Función Error");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonFinalizar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUltimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNueva, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEliminar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButtonNueva)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jCheckBox1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFinalizar)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButton3)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButton4)
                    .addComponent(jButtonSiguiente))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void funcionError(){
        DefaultListModel lista = new DefaultListModel();        
        ArrayList<FuncionError> funError = this.gramatica.getTlr().getTAccion().getFunError();
        StringBuilder string = new StringBuilder();
        int i=0;
        
        while(i < funError.size()){
            string = new StringBuilder();
            int accion;
            string = string.append(funError.get(i).getIdentificador());
            string = string.append(" - ");
            accion = funError.get(i).getAccion();
            if(accion == 1)
                string.append("Insertar un Símbolo en la Entrada: ");
            if(accion == 2)
                string.append("Borrar un Símbolo de la Entrada");
            if(accion == 3)
                string.append("Modificar un Símbolo de la Entrada: ");
            if(accion == 4)
                string.append("Insertar un Símbolo de la Pila: ");
            if(accion == 5)
                string.append("Borrar un Símbolo de la Pila");
            if(accion == 6)
                string.append("Modificar un Símbolo de la Pila: ");
            if(accion == 7)
                string.append("Terminar el análisis");
            if(accion == 1 || accion ==3 || accion ==4 || accion ==6)
                string.append(funError.get(i).getSimbolo().getNombre());
                
            lista.add(i, string);
            i++;            
                        
        }
        this.jList1.setModel(lista);
        
        if(this.jList1.getModel().getSize()!=0){
            this.jButtonFinalizar.setVisible(false);
            this.jButtonUltimo.setVisible(true);
            this.jButtonSiguiente.setEnabled(true);
            this.jButtonNueva.setEnabled(true);
            this.jButtonEliminar.setEnabled(true);
        }else{
            this.jButtonNueva.setEnabled(true);
            this.jButtonEliminar.setEnabled(false);
            this.jButtonFinalizar.setVisible(true);
            this.jButtonUltimo.setVisible(false);
            this.jButtonSiguiente.setEnabled(false);
        }
        
    }
    void setGramatica(Gramatica gr){
        this.ventanaPadre.setGramatica(gr);
        this.gramatica = gr;
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir del asistente de la simulación de la gramática?", "Salir",JOptionPane.YES_NO_OPTION);

        if(conf==0)
          this.ventanaPadre.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.ventanaPadre.cambiarPaso(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.ventanaPadre.cambiarPaso(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        this.ventanaPadre.cambiarPaso(6);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaActionPerformed
        NuevaFuncionError error = new NuevaFuncionError(this.gramatica, this, 1);
        error.setLocationRelativeTo(null);
        error.setVisible(true);
    }//GEN-LAST:event_jButtonNuevaActionPerformed

    private void jCheckBox1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed1
        if(this.jCheckBox1.isSelected()){
            this.jButtonNueva.setEnabled(false);
            this.jButtonEliminar.setEnabled(false);
            this.jButtonFinalizar.setVisible(true);
            this.jButtonUltimo.setVisible(false);
            this.jButtonSiguiente.setEnabled(false);
        }else{                        
            if(this.jList1.getModel().getSize()!=0){
                this.jButtonFinalizar.setVisible(false);
                this.jButtonUltimo.setVisible(true);
                this.jButtonSiguiente.setEnabled(true);
                this.jButtonNueva.setEnabled(true);
                this.jButtonEliminar.setEnabled(true);
            }else{
                this.jButtonNueva.setEnabled(true);
                this.jButtonEliminar.setEnabled(false);
                this.jButtonFinalizar.setVisible(true);
                this.jButtonUltimo.setVisible(false);
                this.jButtonSiguiente.setEnabled(false);
            }            
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed1

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        /*Simulador sim = new Simulador(2, this.gramatica);
        sim.setVisible(true);
        sim.setLocationRelativeTo(null);*/
        this.ventanaPadre.finalizarAsistente();
        this.ventanaPadre.dispose();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        DefaultListModel modelo= null;   
        int seleccion= this.jList1.getSelectedIndex();  
        String funcion = this.jList1.getModel().getElementAt(seleccion).toString();
        ArrayList<FuncionError> funError = this.gramatica.getTlr().getTAccion().getFunError();
        String id = funcion.substring(0, 1);        
        int num = Integer.parseInt(id);
        int i=0;                        
        
        if(seleccion != -1) {           
            modelo=(DefaultListModel)this.jList1.getModel();
            modelo.remove(seleccion);  
            
            while(i < funError.size()){
                if(funError.get(i).getIdentificador() == num){
                    funError.remove(i);
                }else        
                    i++;                                    
            }
            this.gramatica.getTlr().getTAccion().setFunError(funError);
        }
        
        if(this.jList1.getModel().getSize()!=0){
                this.jButtonFinalizar.setVisible(false);
                this.jButtonUltimo.setVisible(true);
                this.jButtonSiguiente.setEnabled(true);
                this.jButtonNueva.setEnabled(true);
                this.jButtonEliminar.setEnabled(true);
            }else{
                this.jButtonNueva.setEnabled(true);
                this.jButtonEliminar.setEnabled(false);
                this.jButtonFinalizar.setVisible(true);
                this.jButtonUltimo.setVisible(false);
                this.jButtonSiguiente.setEnabled(false);
            }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        this.ventanaPadre.cambiarPaso(6);
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonNueva;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
