//SimAS  /  Gramatica
//Consecuente

package es.uco.simas.util.gramatica;

import java.util.ArrayList;

/**
 * @author vanesa
 */
public class Consecuente extends javax.swing.JFrame {

    ArrayList<Simbolo> conjSimbolos = new ArrayList<>();
    
    public Consecuente() {
        initComponents();
    }

    public ArrayList<Simbolo> getConjSimbolos() {
        return conjSimbolos;
    }

    public void setConjSimbolos(ArrayList<Simbolo> conjSimbolos) {
        this.conjSimbolos = conjSimbolos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
