//SimAS  /  Gramatica
//No Terminal

package es.uco.simas.util.gramatica;
import java.util.*;

/**
 * @author vanesa
 */
public class NoTerminal extends Simbolo {

    boolean simboloInicial;
    ArrayList<Terminal> primeros = new ArrayList<>();
    ArrayList<Terminal> siguientes = new ArrayList<>();
    
    public NoTerminal(String nombre, String valor) {
        super(nombre, valor);
        initComponents();
    }

    public boolean getSimboloInicial() {
        return simboloInicial;
    }

    public void setSimboloInicial(boolean simboloInicial) {
        this.simboloInicial = simboloInicial;
    }

    public ArrayList<Terminal> getPrimeros() {
        return primeros;
    }

    public void setPrimeros(ArrayList<Terminal> primeros) {
        this.primeros = primeros;
    }

    public ArrayList<Terminal> getSiguientes() {
        return siguientes;
    }

    public void setSiguientes(ArrayList<Terminal> siguientes) {
        this.siguientes = siguientes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
