// SimAS / Editor
// Panel Creacion Gramática Paso 4

package es.uco.simas.editor;

import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 * @author vanesa
 */
public class PanelCreacionGramaticaPaso4 extends javax.swing.JPanel {

    private VentanaCreacionGramatica ventanaPadre ;
    DefaultListModel noTerminales = new DefaultListModel();
    String simboloInicial = null;
    
    public PanelCreacionGramaticaPaso4(VentanaCreacionGramatica ventanaPadre) {
        super();        
        initComponents();        
        this.ventanaPadre =ventanaPadre;                 
    }
    
    public    String getSimboloInicial( ) {
        if(this.jComboBox1.getModel().getSize()==0)   {
          return null;
   
        } 
        if(this.jComboBox1.getSelectedIndex() == -1 && this.jComboBox1.getModel().getSize()!=0)  {
            return this.jComboBox1.getModel().getElementAt(0).toString();
   
        } 
        if(this.jComboBox1.getSelectedIndex() != -1 && this.jComboBox1.getModel().getSize()!=0) {
            return this.jComboBox1.getSelectedItem().toString();
        }
        return null;
    }
    
    public void setSimboloInicial(String inicial){
        this.simboloInicial= inicial;
    }

    public    void setSimbolosNoTerminales(  DefaultListModel simbolosNoTerminales)  {
        this.noTerminales = simbolosNoTerminales;
        String[] combo = new String[simbolosNoTerminales.getSize()];
        int i= 0;
        int inicial=-1;

         while(true) {
            if(i >= simbolosNoTerminales.getSize())    {
              break;
            }
            if(i < simbolosNoTerminales.getSize())   {
                combo[i] = simbolosNoTerminales.getElementAt(i).toString();
                if(combo[i].equals(this.simboloInicial))
                    inicial=i;
             }
              i = i+1;
         }
         DefaultComboBoxModel nt = new DefaultComboBoxModel(combo);
         this.jComboBox1.setModel(nt);
         if(inicial != -1)
            this.jComboBox1.setSelectedIndex(inicial);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonFin = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonPrimero = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 244, 244));
        setToolTipText("Seleccion Símbolo Inicial");

        jButtonFin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonFin.setForeground(new java.awt.Color(33, 77, 72));
        jButtonFin.setText("Finalizar");
        jButtonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinActionPerformed(evt);
            }
        });

        jButtonAnterior.setForeground(new java.awt.Color(33, 77, 72));
        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/anterior.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(33, 77, 72));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 77, 72));
        jLabel2.setText("Seleccione el símbolo Inicial de la Gramática:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/primero.png"))); // NOI18N
        jButtonPrimero.setToolTipText("Primero");
        jButtonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrimero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFin)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAnterior, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(37, 37, 37))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinActionPerformed
        this.ventanaPadre.finalizarAsistente();
    }//GEN-LAST:event_jButtonFinActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir de la edicion de la gramática?", "Salir",JOptionPane.YES_NO_OPTION);

        if(conf==0)
          this.ventanaPadre.finalizarAsistente();//dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        
        this.ventanaPadre.cambiarPaso(3);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeroActionPerformed
        this.ventanaPadre.cambiarPaso(1);
    }//GEN-LAST:event_jButtonPrimeroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFin;
    private javax.swing.JButton jButtonPrimero;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
