//SimAS  /  Simulador
//Panel nueva simulacion descendente paso 5

package es.uco.simas.simulador;

import es.uco.simas.editor.FuncionError;
import es.uco.simas.editor.TablaPredictiva;
import es.uco.simas.util.gramatica.Gramatica;
import es.uco.simas.util.gramatica.Produccion;
import es.uco.simas.util.gramatica.Terminal;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Vanesa
 */
public class PanelNuevaSimDescPaso5 extends javax.swing.JPanel {

    private VentanaSimuladorDesc ventanaPadre;
    private Gramatica gramatica;
    private DefaultTableModel modeloConjuntos ;
    private TablaPredictiva tpredictiva;
    int red = 0;
    
    public PanelNuevaSimDescPaso5(VentanaSimuladorDesc ventanaPadre) {
        DefaultTableModel tabla = new DefaultTableModel();
        this.modeloConjuntos = tabla;
        initComponents();                
        this.ventanaPadre = ventanaPadre;
        this.gramatica = ventanaPadre.getGramatica();
        this.jButton6.setEnabled(false);
        this.tpredictiva = this.gramatica.getTPredictiva();          
        this.jTable1.setModel(this.tpredictiva.getTabla());
        this.inicializarCombos(this.tpredictiva);                    
        this.anadirTerminales();  
        this.jTable1.setDefaultRenderer (Object.class, new MiRender());
    }    
    
    private void anadirTerminales(){
        ArrayList<Terminal> term = this.ventanaPadre.getGramatica().getTerm();
        DefaultTableModel tabla = this.tpredictiva.getTabla();
        int fila = this.tpredictiva.getTabla().getRowCount();
        int columna = 1;
        int i=0;
        
        while(i < term.size()){            
            Object []  linea = new Object[]  {
                  term.get(i).getNombre()
                 };
            tabla.addRow(linea);     
            
            i++;
        }        
        Object []  linea = new Object[]  {
                  "$"
                 };
            tabla.addRow(linea);
            
        this.tpredictiva.setTabla(tabla);
        i = fila;
        while(i < tabla.getRowCount()-1){                        
            this.tpredictiva.setCeldaPredictiva("<HTML> <FONT COLOR=\"blue\">Emparejar</FONT></HTML>", i, columna);
            i++;
            columna++;            
        }
        this.tpredictiva.setCeldaPredictiva("<HTML> <FONT COLOR=\"blue\">Aceptar</FONT></HTML>", i, columna);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 244, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Incluir Funciones de Error");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/siguiente.png"))); // NOI18N
        jButton2.setEnabled(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/anterior.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/primero.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pulse en la tabla para insertar la funcion de error:");

        jButton6.setText("Eliminar Funcion de Error");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Rellenar con producciones épsilon");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton6)
                .addGap(31, 31, 31)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addComponent(jButton5))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents
    
     private void inicializarCombos(TablaPredictiva tpredictiva) {
        ArrayList<String> listaCombo = new ArrayList(); 
        ArrayList<FuncionError> funError = tpredictiva.getFunError();
        StringBuilder string = new StringBuilder();
        int i= 0;
          
        while(i < funError.size()) { 
            string = new StringBuilder();
            int accion;
            string = string.append(funError.get(i).getIdentificador());
            string = string.append(" - ");
            accion = funError.get(i).getAccion();
            if(accion == 1)
                string.append("Insertar un Símbolo en la Entrada: ");
            if(accion == 2)
                string.append("Borrar un Símbolo de la Entrada");
            if(accion == 3)
                string.append("Modificar un Símbolo de la Entrada: ");
            if(accion == 4)
                string.append("Insertar un Símbolo de la Pila: ");
            if(accion == 5)
                string.append("Borrar un Símbolo de la Pila");
            if(accion == 6)
                string.append("Modificar un Símbolo de la Pila: ");
            if(accion == 7)
                string.append("Terminar el análisis");
            if(accion == 1 || accion ==3 || accion ==4 || accion ==6)
                string.append(funError.get(i).getSimbolo().getNombre());
            
            listaCombo.add(string.toString());                   
            i++;            
        }        
        DefaultComboBoxModel combo = new DefaultComboBoxModel(listaCombo.toArray());                
        this.jComboBox1.setModel(combo);                
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.gramatica.setTPredictiva(this.tpredictiva);
        this.ventanaPadre.finalizarAsistente();
        this.ventanaPadre.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir del asistente de la simulacion de la gramática?", "Salir",JOptionPane.YES_NO_OPTION);

        if(conf==0)
          this.ventanaPadre.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int columna = this.jTable1.getSelectedColumn();
        int fila = this.jTable1.getSelectedRow();
        this.jButton6.setEnabled(false);
        ArrayList<String> term = new ArrayList<>();
        term = buscarTerm();
        int i=0;
        int x=0;
        while(i<term.size()){
            if(this.tpredictiva.getCeldaPredictiva(fila, 0).toString().equals(term.get(i))){
                JOptionPane.showConfirmDialog(null, "Esta fila no se puede rellenar, debido a que el símbolo \""+term.get(i)+"\" no aparece en la parte derecha de una produccion en un lugar que no sea el primero.", "Salir",JOptionPane.CLOSED_OPTION);
                //Esta fila no se puede rellenar, debido a que el símbolo "+term.get(i)+" aparece el primero en una de las producciones.", "Salir",JOptionPane.CLOSED_OPTION);
                x=-1;
                break;
            }else
                i++;
        }
        if(x==0){       
            if(this.tpredictiva.getCeldaPredictiva(fila, columna) == null){            
                String str = "E"+this.jComboBox1.getSelectedItem().toString().substring(0, 1);            
                this.tpredictiva.setCeldaPredictiva(str, fila, columna);            
             //   this.jTable1.setDefaultRenderer (Object.class, new MiRender());
            }
            if(this.tpredictiva.getCeldaPredictiva(fila, columna).toString().startsWith("E")){
                this.jButton6.setEnabled(true);
            }
            this.gramatica.setTPredictiva(this.tpredictiva); 
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private ArrayList<String> buscarTerm(){        
        ArrayList<String> term = new ArrayList<>();
        int i=0;
        while(i< this.gramatica.getPr().size()){
            if(this.gramatica.isTerminal(this.gramatica.getPr().get(i).getConsec().get(0).getNombre()))
                term.add(this.gramatica.getPr().get(i).getConsec().get(0).getNombre());
            i++;
        }
        return term;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.ventanaPadre.cambiarPaso(4);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.ventanaPadre.cambiarPaso(1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int columna = this.jTable1.getSelectedColumn();
        int fila = this.jTable1.getSelectedRow();
        this.tpredictiva.setCeldaPredictiva(null, fila, columna);
        this.jButton6.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ArrayList<Produccion> prod = this.gramatica.getPr();
        int i=0;
        red++;
        
        if(red % 2 != 0 ){ //red es impar: completar con reducciones
            while(i < prod.size()){
                if(prod.get(i).getConsec().get(0).getNombre().equals("\u03b5")){
                    String ant = prod.get(i).getAntec().getSimboloNT().getNombre();
                    int j=0;
                    while(j < this.jTable1.getRowCount()){
                        if(this.jTable1.getValueAt(j, 0).toString().equals(ant)){
                            int k=1;
                            while(k < this.jTable1.getColumnCount()){
                                if(this.jTable1.getValueAt(j, k)==null){
                                     this.jTable1.setValueAt(i+1+"*", j, k);
                                }
                                k++;
                            }

                        }
                        j++;
                    }
                }
                i++;
            }
            this.jButton7.setText("Eliminar producciones épsilon");
        }else{ //red par: Eliminar reducciones
           
           i=0;
           int j=1;
           
           while(i < this.jTable1.getRowCount()){                            
                j=1;
                while(j < this.jTable1.getColumnCount()){   
                    if(this.jTable1.getValueAt(i, j)!=null){
                        if(this.jTable1.getValueAt(i, j).toString().contains("*")){
                            this.jTable1.setValueAt(null, i, j);
                        }
                    }
                    j++;
                }  
                i++;
            }
            this.jButton7.setText("Rellenar con producciones épsilon");
        }
        this.gramatica.setTPredictiva(this.tpredictiva);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
