//SimAS  /  Simulador
//Panel Nueva Simulacion Ascendente paso 2

package es.uco.simas.simulador;

import es.uco.simas.util.gramatica.Gramatica;
import es.uco.simas.util.gramatica.NoTerminal;
import es.uco.simas.util.gramatica.Terminal;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author vanesa
 */
public class PanelNuevaSimAscPaso2 extends javax.swing.JPanel {

    private VentanaSimuladorAsc ventanaPadre;
    private  DefaultTableModel modeloConjuntos ;
    private  JTable tblConjuntos ;    
    
    public PanelNuevaSimAscPaso2(VentanaSimuladorAsc ventanaPadre) {
        DefaultTableModel tabla = new DefaultTableModel();
        this.modeloConjuntos =tabla;
        initComponents();
        
        this.ventanaPadre =ventanaPadre;
        
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(90);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(290);
        this.jTable1.setEnabled(false);
        Gramatica gr = this.ventanaPadre.gramatica;
        
    }
    
    public void construirConjuntos(Gramatica gramatica)  {        
        ArrayList<com.itextpdf.text.Paragraph> construccionConjuntoPrimero= new ArrayList();
        ArrayList<com.itextpdf.text.Paragraph> construccionConjuntoSiguiente= new ArrayList();
        ArrayList<NoTerminal> noTerminales= null;
        ArrayList<Terminal> conjuntoPrimero= null;
        ArrayList<Terminal> conjuntoSiguiente= null;
        ArrayList<Terminal> conjuntoPrimeroSimbolo= null;
        ArrayList<Terminal> conjuntoSiguienteSimbolo= null;        
        Iterator i$= null;
        NoTerminal noTerminal= null;
        String strConjuntoPrimero= null;
        String strConjuntoSiguiente= null;

        int i= 0;
        int j=0;

        this.modeloConjuntos =new DefaultTableModel();
        this.modeloConjuntos.addColumn("Simbolo");
        this.modeloConjuntos.addColumn("Conjunto primero");
        this.modeloConjuntos.addColumn("Conjunto siguiente");
        this.jTable1.setModel(this.modeloConjuntos);
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(95);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(290);
        this.jTable1.setEnabled(false);

        noTerminales = gramatica.getNoTerm();
        
        i=0;
        while(i < noTerminales.size()){
            strConjuntoPrimero = "";
            strConjuntoSiguiente = "";
            noTerminal = noTerminales.get(i);
            conjuntoPrimero = noTerminal.getPrimeros();
            conjuntoSiguiente = noTerminal.getSiguientes();            
          
            j=0;
            while(j < conjuntoPrimero.size()){
                StringBuilder cadena = new StringBuilder();
                strConjuntoPrimero = cadena.append(strConjuntoPrimero).append(" ").append(conjuntoPrimero.get(j).getNombre()).toString();
               
                j++;
            }
            
            j=0;
            while(j < conjuntoSiguiente.size()){
                StringBuilder cadena = new StringBuilder();
                strConjuntoSiguiente = cadena.append(strConjuntoSiguiente).append(" ").append(conjuntoSiguiente.get(j).getNombre()).toString();
               
                j++;
            }                                            
            
            Object []  linea = new Object[]    
            {
              noTerminal.getValor(),          strConjuntoPrimero,          strConjuntoSiguiente
             };
            this.modeloConjuntos.addRow(linea);            
            i++;
        }
        this.ventanaPadre.gramatica = gramatica;        
    }                   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPrimero = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 244, 244));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Símbolo", "Conjunto Primero", "Conjunto Siguiente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Conjunto Primero y Siguiente");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/primero.png"))); // NOI18N
        jButtonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeroActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/anterior.png"))); // NOI18N
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/siguiente.png"))); // NOI18N
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uco/simas/resources/ultimo.png"))); // NOI18N
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPrimero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUltimo)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAnterior)
                        .addComponent(jButtonSiguiente)
                        .addComponent(jButtonUltimo))
                    .addComponent(jButtonCancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtonPrimero)))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir del asistente de la simulacion de la gramática?", "Salir",JOptionPane.YES_NO_OPTION);
        if(conf==0)
          this.ventanaPadre.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeroActionPerformed
        this.ventanaPadre.cambiarPaso(1);
    }//GEN-LAST:event_jButtonPrimeroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        this.ventanaPadre.cambiarPaso(1);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        this.ventanaPadre.cambiarPaso(3);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        
        PanelNuevaSimAscPaso3 paso3 = new PanelNuevaSimAscPaso3(this.ventanaPadre);
        
        PanelNuevaSimAscPaso4 paso4 = new PanelNuevaSimAscPaso4(this.ventanaPadre);
        
        this.ventanaPadre.cambiarPaso(5);
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPrimero;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
