// SimAS / Editor
// Ventana Simbolos No Terminales

package es.uco.simas.editor;

import es.uco.simas.util.gramatica.Gramatica;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 * @author vanesa
 */
public class VentanaSimbolosNoTerminales extends javax.swing.JFrame {

    private  DefaultListModel modeloListaTerminales ;
    private  DefaultListModel modeloListaNoTerminales ;
    private  PanelCreacionGramaticaPaso2 panelPadre ;
    private  Gramatica gramatica;
    
    public VentanaSimbolosNoTerminales(ListModel simbolosNoTerminales,  ListModel simbolosTerminales,  PanelCreacionGramaticaPaso2 ventanaPadre, Gramatica gr) {
    
        int i=0;
        DefaultListModel NoTerminales = new DefaultListModel();
        this.modeloListaNoTerminales =NoTerminales;
        
        while(true)  {
            if(i >= simbolosNoTerminales.getSize())  {
                break;
            }
            if(i < simbolosNoTerminales.getSize()) {
                this.modeloListaNoTerminales.add(i,simbolosNoTerminales.getElementAt(i));
                i = i+1;
            }
        }
              
        initComponents();
        this.jList1.setModel(simbolosNoTerminales);
        this.setResizable(false);
        this.panelPadre =ventanaPadre;
        this.gramatica = gr;
        this.jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Símbolos No Terminales");

        jPanel1.setBackground(new java.awt.Color(233, 244, 244));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonInsertar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEliminar)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertar)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir de la edición de la gramática?", "Salir",JOptionPane.YES_NO_OPTION);

        if(conf==0){           
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        String elemento = jTextField1.getText();
        int encontrado= 0;
        int i= 0;
        
        if(elemento.equals("")){
            encontrado =1;
        }else{
            while(true){
                if(i >= this.modeloListaNoTerminales.getSize()) {
                    break;
                }
                if(i < this.modeloListaNoTerminales.getSize())  {
                    if(this.modeloListaNoTerminales.getElementAt(i).equals(elemento)) {
                        encontrado=1;
                    }
                i = i+1;
                }
            }
        }
        if(encontrado==0)  {
            this.modeloListaNoTerminales.add(this.modeloListaNoTerminales.getSize(),elemento);
            this.jList1.setModel(this.modeloListaNoTerminales);
        }
        this.jTextField1.requestFocus();
        this.jTextField1.setText("");
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        DefaultListModel modelo= null;
        DefaultListModel producciones = this.panelPadre.getProducciones();                
        String[] pr;
        ArrayList<String> prod = new ArrayList();
        String nt;
        int seleccion= 0;
        nt = this.jList1.getSelectedValue().toString();
        
        
        seleccion=this.jList1.getSelectedIndex();
        if(seleccion != -1) {
            if(producciones != null){
                int i=0;                
                while(i< producciones.size()){
                    int j=0;
                    pr = (producciones.getElementAt(i).toString()).split(" ");                    
                    while(j < pr.length){
                        if(pr[j].equals(this.jList1.getSelectedValue())){                            
                            prod.add(producciones.getElementAt(i).toString());                                                                                            
                        }
                        j++;
                    }
                    i++;
                }
            }
            if(prod.size()>0){                
                int conf = JOptionPane.showConfirmDialog(null, "El símbolo "+nt+" ha sido usado, si lo elimina también se eliminarán las producciones en las que aparezca, ¿desea eliminarlo?", "Símbolo usado",JOptionPane.YES_NO_OPTION);
                if(conf==0){                    
                    int k=0;
                    while(k < prod.size()){                        
                        int l=0;
                        while(l < producciones.size()){
                            if(prod.get(k).equals(producciones.get(l).toString())){
                                producciones.remove(l);
                                break;
                            }else
                                l++;
                        }                        
                        k++;
                    }
                    
                    this.panelPadre.setProducciones(producciones);
                    modelo=(DefaultListModel)this.jList1.getModel();
                    modelo.remove(seleccion);                     
                }
                
            }else{
                modelo=(DefaultListModel)this.jList1.getModel();
                modelo.remove(seleccion);   
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(this.panelPadre!=  null)   {
            if(this.jList1.getModel().getSize() > 0)  {
                this.panelPadre.asignarListaSimbolosNoTerminales((DefaultListModel)this.jList1.getModel());
            }
        }else{
            this.gramatica.setNoTerminales(modeloListaNoTerminales);
        }
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosNoTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosNoTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosNoTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosNoTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new VentanaSimbolosNoTerminales().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}