// SimAS / Editor
// Ventana Simbolos Terminales

package es.uco.simas.editor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 * @author vanesa
 */
public class VentanaSimbolosTerminales extends javax.swing.JFrame {

  private  DefaultListModel modeloListaTerminales ;
  private  DefaultListModel modeloListaNoTerminales ;
  private  PanelCreacionGramaticaPaso2 panelPadre ;

  
  public VentanaSimbolosTerminales(ListModel simbolosTerminales,  ListModel simbolosNoTerminales,  PanelCreacionGramaticaPaso2 ventanaPadre) {
 
     int i= 0;
     
     DefaultListModel list = new DefaultListModel();
     this.modeloListaTerminales =list;
     i=0;
     while(true){
        if(i >= simbolosTerminales.getSize()) {
            break;
        }
        if(i < simbolosTerminales.getSize())  {
            this.modeloListaTerminales.add(i,simbolosTerminales.getElementAt(i));
            i = i+1;    
        }
    }
    DefaultListModel lista = new DefaultListModel();
    this.modeloListaNoTerminales =lista;
    i=0;
    while(true) {
      if(i >= simbolosNoTerminales.getSize()) {
        break;
      }
      if(i < simbolosNoTerminales.getSize())  {
        this.modeloListaNoTerminales.add(i,simbolosNoTerminales.getElementAt(i));
        i = i+1;    
      }
    }
    
    initComponents();
    this.jList1.setModel(simbolosTerminales);

    this.setResizable(false);
    this.panelPadre =ventanaPadre;
    this.jTextField1.setText("");
   // this.btnTerminal13.setText("\u03b5");
  //  this.btnTerminal13.setToolTipText("<html>Inserta el s\u00edmbolo <b>\u03b5</b>.</html>");
   // this.txtSimboloTerminal.requestFocus();
  //  this.estaVentana =this;
   /* VentanaSimbolosTerminales prueba = new VentanaSimbolosTerminales(this, null, null);
    this.jTextField1.addKeyListener(prueba);
    VentanaGestionarSimbolosTerminales$4 JdecGenerated190 = new VentanaGestionarSimbolosTerminales$4(this);
    this.txtSimboloTerminal.addActionListener(JdecGenerated190);
    return;*/
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Símbolos Terminales");

        jPanel1.setBackground(new java.awt.Color(233, 244, 244));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Símbolos Terminales Predefinidos");

        jButton1.setText(" + ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(" - ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(" * ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(" / ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(" ( ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(" ) ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(" { ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(" } ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(" = ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText(" . ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText(" , ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText(" ; ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText(" : ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setDropMode(javax.swing.DropMode.INSERT);
        jScrollPane2.setViewportView(jList1);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButtonInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminar))))
                    .addComponent(jScrollPane2))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertar)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int conf = JOptionPane.showConfirmDialog(null, "¿Desea salir de la edición de la gramática?", "Salir",JOptionPane.YES_NO_OPTION);

        if(conf==0)
            this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
     /*   DefaultListModel listModel = new DefaultListModel();
        String elemento = jTextField1.getText();
        listModel.addElement(elemento);*/
        String elemento = jTextField1.getText();
        int encontrado= 0;
        int i= 0;
        
        if(elemento.equals("")){
            encontrado =1;
        }else{
        while(true)    {
            if(i >= this.modeloListaTerminales.getSize())  {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals(elemento)) {
                    encontrado=1;
                }
                 
            i = i+1;
        //continue  ;
            }
      }
   
    }
    if(encontrado==0)
    {
      this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),elemento);
      this.jList1.setModel(this.modeloListaTerminales);
   
    }
    this.jTextField1.requestFocus();
    this.jTextField1.setText("");
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int encontrado= 0;
        int i= 0;
        encontrado=0;
        i=0;
        while(true)  {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals("+")) {
                    encontrado=1;
                }
            i = i+1;    
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"+");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int encontrado= 0;
        int i= 0;
        while(true)  {
            if(i >= this.modeloListaTerminales.getSize())  {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals("-")) {
                    encontrado=1;
                }
            i = i+1;    
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"-");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(this.panelPadre!=  null)  {
            if(this.jList1.getModel().getSize() > 0)  { 
                this.panelPadre.asignarListaSimbolosTerminales((DefaultListModel)this.jList1.getModel());
             }
       }
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        DefaultListModel modelo= null;
        DefaultListModel producciones = this.panelPadre.getProducciones();                
        String[] pr;
        ArrayList<String> prod = new ArrayList();
        String nt;
        int seleccion= 0;
        nt = this.jList1.getSelectedValue().toString();
        
        
        seleccion=this.jList1.getSelectedIndex();
        if(seleccion != -1) {
            if(producciones != null){
                int i=0;                
                while(i< producciones.size()){
                    int j=0;
                    pr = (producciones.getElementAt(i).toString()).split(" ");                    
                    while(j < pr.length){
                        if(pr[j].equals(this.jList1.getSelectedValue())){                            
                            prod.add(producciones.getElementAt(i).toString());                                                                                            
                        }
                        j++;
                    }
                    i++;
                }
            }
            if(prod.size()>0){                
                int conf = JOptionPane.showConfirmDialog(null, "El símbolo "+nt+" ha sido usado, si lo elimina también se eliminarán las producciones en las que aparezca, ¿desea eliminarlo?", "Símbolo usado",JOptionPane.YES_NO_OPTION);
                if(conf==0){                    
                    int k=0;
                    while(k < prod.size()){                        
                        int l=0;
                        while(l < producciones.size()){
                            if(prod.get(k).equals(producciones.get(l).toString())){
                                producciones.remove(l);
                                break;
                            }else
                                l++;
                        }                        
                        k++;
                    }
                    
                    this.panelPadre.setProducciones(producciones);
                    modelo=(DefaultListModel)this.jList1.getModel();
                    modelo.remove(seleccion);                     
                }
                
            }else{
                modelo=(DefaultListModel)this.jList1.getModel();
                modelo.remove(seleccion);   
            }
        }
        
        
        
        /*DefaultListModel modelo= null;
        int seleccion= 0;
        seleccion=this.jList1.getSelectedIndex();
        
        if(seleccion != -1)  {
            modelo=(DefaultListModel)this.jList1.getModel();
            modelo.remove(seleccion);
        }*/
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize())  {
                if(this.modeloListaTerminales.getElementAt(i).equals("*")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0){
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"*");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()){
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals("/")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"/");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int encontrado= 0;
        int i= 0;
        
        while(true) {
            if(i >= this.modeloListaTerminales.getSize()){
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals("(")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"(");
            this.jList1.setModel(this.modeloListaTerminales);   
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals(")")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),")");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true)  {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals("{")) {
                    encontrado=1;
                }
            i = i+1;    
            }
        }
        if(encontrado==0){
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"{");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals("}")) {
                    encontrado=1;
                }
            i = i+1;    
            }
        }
        if(encontrado==0)  {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"}");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize())  {
                if(this.modeloListaTerminales.getElementAt(i).equals("=")) {
                    encontrado=1;
                }
            i = i+1;    
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),"=");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize())  {
                if(this.modeloListaTerminales.getElementAt(i).equals(".")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),".");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true)  {
            if(i >= this.modeloListaTerminales.getSize())  {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals(",")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0)  {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),",");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals(";")) {
                    encontrado=1;
                }
            i = i+1;
            }
        }
        if(encontrado==0)  {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),";");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int encontrado= 0;
        int i= 0;

        while(true) {
            if(i >= this.modeloListaTerminales.getSize()) {
                break;
            }
            if(i < this.modeloListaTerminales.getSize()) {
                if(this.modeloListaTerminales.getElementAt(i).equals(":")) {
                    encontrado=1;
                }
            i = i+1;    
            }
        }
        if(encontrado==0) {
            this.modeloListaTerminales.add(this.modeloListaTerminales.getSize(),":");
            this.jList1.setModel(this.modeloListaTerminales);
        }
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSimbolosTerminales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new VentanaSimbolosTerminales().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
